---
repos:
  - repo: https://github.com/zricethezav/gitleaks
    rev: v8.8.2
    hooks:
      - id: gitleaks
  # - repo: https://github.com/adrienverge/yamllint
  #   rev: v1.27.1
  #   hooks:
  #     - id: yamllint
  - repo: https://github.com/antonbabenko/pre-commit-terraform
    rev: v1.96.1
    hooks:
      - id: terraform_fmt
      - id: terraform_docs
