---
version: "3"
silent: true

tasks:
  pre-commit:init:
    desc: Initiate and install dependencies
    cmds:
      - pre-commit install

  pre-commit:check:
    desc: Check all pre-commit hooks
    cmds:
      - pre-commit run -a
