---
# yaml-language-server: $schema=../../rule-groups/schema.json
- name: metrics
  interval_seconds: 300
  rules:
    - name: node-metrics-no-data
      annotations:
        summary: "Node metrics returns NoData"
        description: "The node-exporter metrics has been no data for 5 minutes. Please check if node-exporter or Prometheus is working."
      condition: "A"
      datas:
        - ref_id: "A"
          model:
            expr: "absent(node_uname_info) or vector(0)"
            instant: true
      no_data_state: "Alerting"
      exec_err_state: "Error"
      for: "5m"
      labels:
        severity: "critical"
- name: filesystem
  interval_seconds: 300
  rules:
    - name: node-fs-space-warning
      annotations:
        summary: "Filesystem has less than 25% space left"
        description: ""
      condition: A
      datas:
        - ref_id: A
          model:
            expr: |
              (
                node_filesystem_avail_bytes{fstype!="",mountpoint!="", ${node_selectors}} 
                / node_filesystem_size_bytes{${node_selectors}} * 100 < bool 25
              and
                node_filesystem_readonly{fstype!="",mountpoint!="", ${node_selectors}} == 0
              )
            instant: true
      no_data_state: "NoData"
      exec_err_state: "Error"
      for: 5m
      labels:
        severity: warning
    - name: node-fs-space-critical
      annotations:
        summary: "Filesystem has less than 5% space left"
        description: ""
      condition: A
      datas:
        - ref_id: A
          model:
            expr: |
              (
                node_filesystem_avail_bytes{fstype!="",mountpoint!="", ${node_selectors}}
                / node_filesystem_size_bytes{${node_selectors}} * 100 < 5
              and
                node_filesystem_readonly{fstype!="",mountpoint!="", ${node_selectors}} == 0
              )
            instant: true
      no_data_state: "NoData"
      exec_err_state: "Error"
      for: 5m
      labels:
        severity: critical
    - name: node-fs-files-warning
      annotations:
        summary: "Filesystem has less than 25% inodes left"
        description: ""
      condition: A
      datas:
        - ref_id: A
          model:
            expr: |
              (
                node_filesystem_files_free{fstype!="",mountpoint!="", ${node_selectors}}
                / node_filesystem_files{fstype!="",mountpoint!="", ${node_selectors}} * 100 < 25
                  and
                node_filesystem_readonly{fstype!="",mountpoint!="", ${node_selectors}} == 0
              )
            instant: true
      no_data_state: "NoData"
      exec_err_state: "Error"
      for: "5m"
      labels:
        severity: warning
    - name: node-fs-files-critical
      annotations:
        summary: "Filesystem has less than 5% inodes left"
        description: ""
      condition: A
      datas:
        - ref_id: A
          model:
            expr: |
              (
                node_filesystem_files_free{fstype!="",mountpoint!="", ${node_selectors}}
                / node_filesystem_files{fstype!="",mountpoint!="", ${node_selectors}} * 100 < 5
                  and
                node_filesystem_readonly{fstype!="",mountpoint!="", ${node_selectors}} == 0
              )
            instant: true
      no_data_state: "NoData"
      exec_err_state: "Error"
      for: "5m"
      labels:
        severity: critical
- name: network
  interval_seconds: 300
  rules:
    - name: node-network-receive-err
      annotations:
        summary: "Network interface is reporting many receive errors"
        description: ""
      condition: A
      datas:
        - ref_id: A
          model:
            expr: |
              rate(node_network_receive_errs_total{${node_selectors}}[5m])
              / rate(node_network_receive_packets_total{${node_selectors}}[5m])
              > bool 0.01
            instant: true
      no_data_state: "NoData"
      exec_err_state: "Error"
      for: 5m
      labels:
        severity: warning
    - name: node-network-transmit-err
      annotations:
        summary: "Network interface is reporting many transmit errors"
        description: ""
      condition: A
      datas:
        - ref_id: A
          model:
            expr: |
              rate(node_network_transmit_errs_total{${node_selectors}}[5m]) 
              / rate(node_network_transmit_packets_total{${node_selectors}}[5m]) 
              > bool 0.01
            instant: true
      no_data_state: "NoData"
      exec_err_state: "Error"
      for: 5m
      labels:
        severity: warning
    - name: node-high-number-conntrack-entries-used
      annotations:
        summary: "Number of conntrack are getting close to the limit"
        description: ""
      condition: A
      datas:
        - ref_id: A
          model:
            expr: |
              node_nf_conntrack_entries{${node_selectors}} 
              / node_nf_conntrack_entries_limit{${node_selectors}} * 100 
              > bool 75
            instant: true
      no_data_state: "NoData"
      exec_err_state: "Error"
      for: 5m
      labels:
        severity: warning
- name: cpu
  interval_seconds: 300
  rules:
    - name: node-cpu-high-usage
      annotations:
        summary: "Node is under high CPU usage"
        description: ""
      condition: A
      datas:
        - ref_id: A
          model:
            expr: |
              sum without(mode) (avg without (cpu) (rate(node_cpu_seconds_total{mode!="idle", ${node_selectors}}[5m]))) * 100
              > bool 90
            instant: true
      no_data_state: "NoData"
      exec_err_state: "Error"
      for: 5m
      labels:
        severity: warning
- name: memory
  interval_seconds: 300
  rules:
    - name: node-memory-major-pages-faults
      annotations:
        summary: "Memory major page faults are occurring at very high rate"
        description: ""
      condition: A
      datas:
        - ref_id: A
          model:
            expr: |
              rate(node_vmstat_pgmajfault{${node_selectors}}[5m]) > bool 500
            instant: true
      no_data_state: "NoData"
      exec_err_state: "Error"
      for: 5m
      labels:
        severity: warning
    - name: node-memory-high-utilization
      annotations:
        summary: "Node is running out of memory"
        description: ""
      condition: A
      datas:
        - ref_id: A
          model:
            expr: |
              (1 - (node_memory_MemAvailable_bytes{${node_selectors}}/node_memory_MemTotal_bytes{${node_selectors}})) * 100 
              > bool 75
            instant: true
      no_data_state: "NoData"
      exec_err_state: "Error"
      for: 5m
      labels:
        severity: warning
- name: disk
  interval_seconds: 300
  rules:
    - name: node-disk-io-saturation
      annotations:
        summary: "Disk IO queue is high"
        description: ""
      condition: A
      datas:
        - ref_id: A
          model:
            expr: |
              rate(node_disk_io_time_weighted_seconds_total{device!="", ${node_selectors}}[5m]) 
              > bool 10
            instant: true
      no_data_state: "NoData"
      exec_err_state: "Error"
      for: 5m
      labels:
        severity: 5m
- name: system
  interval_seconds: 300
  rules:
    - name: node-raid-degraded
      annotations:
        summary: "RAID Array is degraded"
        description: ""
      condition: A
      datas:
        - ref_id: A
          model:
            expr: |
              node_md_disks_required{device!="", ${node_selectors}} 
              - ignoring (state) (node_md_disks{state="active",device!="", ${node_selectors}}) 
              > bool 0
            instant: true
      no_data_state: "NoData"
      exec_err_state: "Error"
      for: 5m
      labels:
        severity: critical
    - name: node-raid-disk-failure
      annotations:
        summary: "Failed device in RAID array"
        description: ""
      condition: A
      datas:
        - ref_id: A
          model:
            expr: node_md_disks{state="failed",device!="", ${node_selectors}} > bool 0
            instant: true
      no_data_state: "NoData"
      exec_err_state: "Error"
      for: 5m
      labels:
        severity: critical
    - name: node-clock-skew-dected
      annotations:
        summary: "Clock skew detected"
        description: ""
      condition: A
      datas:
        - ref_id: A
          model:
            expr: abs(node_timex_offset_seconds{${node_selectors}}) > bool 0.05
            instant: true
      no_data_state: "NoData"
      exec_err_state: "Error"
      for: 5m
      labels:
        severity: warning
    - name: node-clock-not-synchronising
      annotations:
        summary: "Clock is not synchronizing"
        description: ""
      condition: A
      datas:
        - ref_id: A
          model:
            expr: node_timex_maxerror_seconds{${node_selectors}} >= bool 16
            instant: true
      no_data_state: "NoData"
      exec_err_state: "Error"
      for: 5m
      labels:
        severity: warning
    - name: node-clock-error
      annotations:
        summary: ""
        description: ""
      condition: A
      datas:
        - ref_id: A
          model:
            expr: min_over_time(node_timex_sync_status{${node_selectors}}[5m]) == bool 0
            instant: true
      no_data_state: "NoData"
      exec_err_state: "Error"
      for: 5m
      labels:
        severity: warning
    - name: node-text-file-collector-scrape-err
      annotations:
        summary: "Node-exporter text file collector failed to scrape"
        description: ""
      condition: A
      datas:
        - ref_id: A
          model:
            expr: node_textfile_scrape_error{${node_selectors}} == bool 1
            instant: true
      no_data_state: "NoData"
      exec_err_state: "Error"
      for: 5m
      labels:
        severity: warning
    - name: node-file-descriptor-limit-warning
      annotations:
        summary: "Kernel is predicted to exhaust file descriptors limit soon"
        description: ""
      condition: A
      datas:
        - ref_id: A
          model:
            expr: |
              node_filefd_allocated{${node_selectors}}/node_filefd_maximum{${node_selectors}}*100
              > bool 70
            instant: true
      no_data_state: "NoData"
      exec_err_state: "Error"
      for: 5m
      labels:
        severity: warning
    - name: node-file-descriptor-limit-critical
      annotations:
        summary: "Kernel is predicted to exhaust file descriptors limit soon"
        description: ""
      condition: A
      datas:
        - ref_id: A
          model:
            expr: |
              node_filefd_allocated{${node_selectors}}/node_filefd_maximum{${node_selectors}}*100
              > bool 90
            instant: true
      no_data_state: "NoData"
      exec_err_state: "Error"
      for: 5m
      labels:
        severity: critical
    - name: node-systemd-service-failed
      annotations:
        summary: "Systemd service has entered failed state"
        description: ""
      condition: A
      datas:
        - ref_id: A
          model:
            expr: node_systemd_unit_state{state="failed", ${node_selectors}} == bool 1
            instant: true
      no_data_state: "NoData"
      exec_err_state: "Error"
      for: 5m
      labels:
        severity: warning
