---
# yaml-language-server: $schema=../../rule-groups/schema.json
- name: metrics-check
  interval_seconds: 300
  rules:
    - name: volsync-no-data
      annotations:
        summary: "Volsync metrics returns NoData"
        description: >
          Volsync metrics has been no data for 5 minutes.
          Please check if volsync or prometheus is working.
      condition: "Z"
      datas:
        - ref_id: "Z"
          model:
            expr: absent(volsync_volume_out_of_sync) or vector(0)
            instant: true
      no_data_state: "Alerting"
      exec_err_state: "Error"
      for: "5m"
      labels:
        severity: critical
- name: volsync
  interval_seconds: 300
  rules:
    - name: volsync-out-of-sync
      annotations:
        summary: "Volsync job(s) is failed"
        description: >
          The volsync job {{ $labels.obj_namespace }}/{{ $labels.obj_name }} is failed.
      condition: Z
      datas:
        - ref_id: A
          model:
            expr: volsync_volume_out_of_sync{${volsync_selectors}}
        - ref_id: B
          model:
            type: reduce
            expression: A
            reducer: last
        - ref_id: Z
          model:
            type: math
            expression: "$B == 1"
      no_data_state: "NoData"
      exec_err_state: "Error"
      for: "0s"
      labels:
        severity: warning
    - name: volsync-too-many-failure
      annotations:
        summary: "Volsync job(s) has failed more than 5 times"
        description: >
          The volsync job {{ $labels.obj_namespace }}/{{ $labels.obj_name }} is failed for more than 5 times.
      condition: Z
      datas:
        - ref_id: "A"
          model:
            expr: volsync_missed_intervals_total{${volsync_selectors}}
        - ref_id: "B"
          model:
            type: reduce
            expression: "A"
            reducer: last
        - ref_id: "Z"
          model:
            type: math
            expression: "$B >= 5"
      no_data_state: "NoData"
      exec_err_state: "Error"
      for: "0s"
      labels:
        severity: critical
